menubar:
  columns: 4
  items:
    - id: home
      theme: ''
      title: 主页
      icon: ''
      url: /
    - id: archives
      theme: ''
      title: 归档
      icon: ''
      url: /archives
    - id: tags
      theme: ''
      title: 标签
      icon: ''
      url: /tags
    - id: about
      theme: ''
      title: 关于
      icon: ''
      url: /about