menubar:
  columns: 4
  items:
    - id: home
      theme: ''
      title: 主页
      icon: ''
      url: /
    - id: links
      theme: ''
      title: 友链
      icon: ''
      url: /links
    - id: tags
      theme: ''
      title: 标签
      icon: ''
      url: /tags
    - id: about
      theme: ''
      title: 关于
      icon: ''
      url: /about